export {default as MailIcon} from './Mail';
export {default as Password} from './Password';
export {default as Name} from './Name';
export {default as Eye} from './Eye';
export {default as HomeIcon} from './Home';
export {default as PersonIcon} from './Person';
export {default as HeartIcon} from './Heart';
export {default as PlusIcon} from './Plus';
export {default as CaptureIcon} from './Capture';
